#!/usr/bin/env python
##############################################################################
#
# Copyright 2016 KPMG Advisory N.V. (unless otherwise stated)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
##############################################################################
"""
Simple script to enable the user to see what linux version KTB thinks they are using
"""
import os
import sys
import __future__

installfrom = os.path.realpath(os.sep.join(__file__.split(os.sep)[:-2]))
if installfrom == "":
    installfrom = ".."
if installfrom.endswith("scripts"):
    installfrom = installfrom[:-len("scripts")]
conflocation = installfrom + os.sep + "config" + os.sep
conflocation = os.path.realpath(conflocation)
sys.path.append(conflocation)
topdir = os.getcwd()

import kaveinstall as li

print(li.linuxVersion)