# KaveToolbox 2.2-Beta on ubuntu 16
FROM kave/kavetoolbox:2.2-Beta.u16.node
MAINTAINER KAVE <kave@kpmg.com>
RUN apt-get update
RUN wget http://repos:kaverepos@repos.dna.kpmglab.com/noarch/KaveToolbox/2.2-Beta/kavetoolbox-installer-2.2-Beta.sh
RUN /bin/bash kavetoolbox-installer-2.2-Beta.sh --clean-before
